### ISSUE TITLE
Edit Mod Configuration error

### ISSUE THREAD

**Issue by bofhlusr** [Jonitr0/WarnoModEditor#6]
Just got this error, when pressing Ctrl-Alt-C (Edit, Edit Mod Configuration)
WME v0.3.1b

<class 'NameError'>: name 'edit_config_dialog' is not defined
Stacktrace:
  File "src\wme_widgets\wme_menu_bar.py", line 221, in on_edit_config_action

**Comment by Jonitr0** [comment]
Yeah I screwed up a rename, sorry about that. I unfortunately cannot publish a fix before next week

**Comment by bofhlusr** [comment]
Hi Jonas,

I also just noticed that saving the Conquest Score in WME should, but is
not adjusting; the Score Limit value in the game.

I'm wondering if WME is saving it to the appropriate ndf file.  What is the
name of the ndf file and the variable field that I should be looking for?

Thanks and have a fantastic weekend!

George

**Comment by bofhlusr** [comment]
FYI...

[image: image.png]

**Comment by Jonitr0** [comment]
First of all, thanks for reporting these issues. It really helps me to keep WME working.

The mod configuration error should be fixed in 0.3.1c.
I unfortunately cannot recreate any issue with the Game Settings Editor. Are you sure the mod is generated and enabled? Which settings did you want to implement?
Anyway, you'll find the relevant data in **GDConstantes.ndf** in the variable **ConquestPossibleScores**.

**Comment by Jonitr0** [comment]
I'll close this for now as the config error is fixed

**Comment by bofhlusr** [comment]
Thank you.

Happy Holidays to you!
